version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment: 
      - ZOO_ENABLE_AUTH=no
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'

  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes    
    ports:
      - '9092:9092'

  redis:
    image: redis
    ports: 
      - '6379:6379'

  # transactions:
  #   build: ./transactions
  #   depends_on:
  #     - kafka